#!/usr/bin/env python

import glob
import imp
import os
from argparse import ArgumentParser

ROOT = os.path.dirname(os.path.realpath(__file__))
TESTS = sorted([os.path.splitext(os.path.basename(x))[0] for x in glob.glob(os.path.join(ROOT, 'tests', '*.py'))])

parser = ArgumentParser(description='Test various microarchitecture parameters')
parser.add_argument('test', nargs='+', help='run test TEST', metavar='TEST', 
        choices=TESTS + ['all'])

if __name__ == "__main__":
    args = parser.parse_args()
    tests = set(args.test)
    if 'all' in tests: tests = set(TESTS)
    for test in tests:
        test_module = imp.load_source(test, os.path.join(ROOT, 'tests', test + ".py"))
        test_module.run_tests()
